/* tslint:disable */
/* eslint-disable */
export function initialize(user_name: string, user_id: string): void;
export function send_message(room_id: any, content: any, message_id: any): void;
export function send_typing_indicator(room_id: any, is_typing: any): void;
export function get_messages(room_id: any): any;
export function join_room(room_id: any, signal_data: string): string;
export function create_room_with_id(room_id: any): void;
export function get_app_state(): any;
export function get_app_config(): any;
export function get_current_user_id(): string;
export function get_current_room_id(): string;
export function set_current_room_id(room_id: string): void;
export function update_user_session(name: string, user_id: string): void;
export function set_typing_status(is_typing: boolean): void;
export function get_room_history_list(): any;
export function add_room_to_history(room_id: string, display_name?: string | null): void;
export function remove_room_from_history(room_id: string): void;
export function get_room_metadata(room_id: string): any;
export function get_draft_messages(): any;
export function set_draft_message(peer_id: string, content: string, sender_name: string): void;
export function clear_draft_message(peer_id: string): void;
export function clear_all_draft_messages(): void;
export function get_connected_peers(): any;
export function add_connected_peer(peer_id: string): void;
export function remove_connected_peer(peer_id: string): void;
export function clear_all_connected_peers(): void;
export function generate_uuid(): any;
export function get_room_from_url(): string;
export function update_url_with_room(room_id: string): void;
export function validate_room_id(room_id: string): string;
export function validate_username(username: string): string;
export function validate_message(message: string): string;
export function sanitize_html_content(html: string): string;
export function validate_url_param(param: string): any;
export function generate_secure_room_id(): string;
export function check_rate_limit(key: string, max_attempts: number, window_ms: number): boolean;
export function validate_file(file_name: string, file_size: number, mime_type: string): boolean;
export function detect_attack_patterns(input: string): any;
export function validate_json_input(json_str: string, max_size: number): any;
export function validate_input_batch(input_type: string, values: any): any;
export function set_message_manager_user(user_id: string): void;
export function send_message_enhanced(room_id: string, content: string, message_id: string): any;
export function receive_message_from_peer(message_data: any): boolean;
export function get_room_messages(room_id: string, limit?: number | null): any;
export function edit_message(room_id: string, message_id: string, new_content: string): void;
export function delete_message(room_id: string, message_id: string): void;
export function add_message_reaction(room_id: string, message_id: string, emoji: string, user_id: string): void;
export function handle_typing_indicator(room_id: string, user_id: string, is_typing: boolean): void;
export function get_typing_users(room_id: string): any;
export function get_messages_for_sync(room_id: string, after_timestamp: number, limit: number): any;
export function get_room_message_stats(room_id: string): any;
export function create_sync_request(room_id: string, last_sync: number, message_count: number): any;
export function handle_sync_request(request_data: any): any;
export function save_room_messages_to_storage(room_id: string): void;
export function load_room_messages_from_storage(room_id: string): boolean;
export function initialize_p2p_manager(client_id: string, room_id: string): void;
export function add_known_peer(peer_id: string): boolean;
export function remove_peer_from_network(peer_id: string): void;
export function update_peer_connection_state(peer_id: string, state: string): void;
export function should_initiate_connection_to_peer(peer_id: string): boolean;
export function get_connection_decision(peer_id: string): any;
export function get_connected_peer_list(): any;
export function record_peer_message_sent(peer_id: string, size_bytes: number): void;
export function record_peer_message_received(peer_id: string, size_bytes: number): void;
export function update_peer_latency(peer_id: string, latency_ms: number): void;
export function needs_mesh_repair(): boolean;
export function get_mesh_repair_plan(): any;
export function get_p2p_network_stats(): any;
export function handle_connection_failure(peer_id: string): any;
export function set_connection_strategy(strategy: string): void;
export function cleanup_stale_peers(timeout_minutes: number): number;
export function get_best_peers_for_broadcast(max_peers: number): any;
export function should_send_to_peer(peer_id: string, message_priority: number): boolean;
export function get_broadcast_plan(redundancy_level: number): any;
export function initialize_logger(is_development: boolean, debug_enabled: boolean): void;
export function set_log_context(user_id?: string | null, room_id?: string | null, component?: string | null): void;
export function log_debug(component: string, message: string): void;
export function log_info(component: string, message: string): void;
export function log_warn(component: string, message: string): void;
export function log_error(component: string, message: string): void;
export function log_with_data(level: string, component: string, message: string, data: string): void;
export function start_log_group(label: string): void;
export function end_log_group(): void;
export function log_table(data: any): void;
export function get_log_entries(filter_json?: string | null): any;
export function clear_log_buffer(): void;
export function export_logs_json(filter_json?: string | null): string;
export function export_recent_logs_json(count: number): string;
export function get_log_statistics(): any;
export function enable_debug_logging(): void;
export function disable_debug_logging(): void;
export function configure_logger(max_entries: number, console_output: boolean, buffer_logs: boolean, auto_export_errors: boolean): void;
export function search_logs(query: string, limit?: number | null): any;
export function get_logs_by_component(component: string, limit?: number | null): any;
export function get_error_summary(last_n_minutes: number): any;
export function create_debug_report(): string;
export function generate_room_encryption_key(room_id: string): string;
export function encrypt_message_content(message: string, key_id?: string | null): string;
export function decrypt_message_content(encrypted_data: string): string;
export function export_encryption_key(key_id: string, password?: string | null): string;
export function import_encryption_key(exported_key: string, password?: string | null): string;
export function list_encryption_keys(): any;
export function delete_encryption_key(key_id: string): boolean;
export function initialize_storage(database_name: string, version: number): void;
export function store_message_persistent(message_data: any): void;
export function get_stored_messages(room_id: string, limit?: number | null): any;
export function store_room_persistent(room_data: any): void;
export function get_stored_room(room_id: string): any;
export function list_stored_rooms(): any;
export function cleanup_old_storage_data(days_old: number): number;
export function start_performance_monitoring(): void;
export function record_performance_metric(name: string, value: number, unit: string, category: string): void;
export function get_performance_summary(): any;
export function start_performance_timer(label: string): void;
export function end_performance_timer(label: string): number | undefined;
export function increment_performance_counter(name: string): void;
export function get_performance_counter(name: string): bigint;

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
  readonly initialize: (a: number, b: number, c: number, d: number) => [number, number];
  readonly send_message: (a: any, b: any, c: any) => [number, number];
  readonly send_typing_indicator: (a: any, b: any) => [number, number];
  readonly get_messages: (a: any) => any;
  readonly join_room: (a: any, b: number, c: number) => [number, number, number, number];
  readonly create_room_with_id: (a: any) => [number, number];
  readonly get_app_state: () => any;
  readonly get_app_config: () => any;
  readonly get_current_user_id: () => [number, number];
  readonly get_current_room_id: () => [number, number];
  readonly set_current_room_id: (a: number, b: number) => [number, number];
  readonly update_user_session: (a: number, b: number, c: number, d: number) => [number, number];
  readonly set_typing_status: (a: number) => [number, number];
  readonly get_room_history_list: () => any;
  readonly add_room_to_history: (a: number, b: number, c: number, d: number) => [number, number];
  readonly remove_room_from_history: (a: number, b: number) => [number, number];
  readonly get_room_metadata: (a: number, b: number) => any;
  readonly get_draft_messages: () => any;
  readonly set_draft_message: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
  readonly clear_draft_message: (a: number, b: number) => [number, number];
  readonly clear_all_draft_messages: () => [number, number];
  readonly get_connected_peers: () => any;
  readonly add_connected_peer: (a: number, b: number) => [number, number];
  readonly remove_connected_peer: (a: number, b: number) => [number, number];
  readonly clear_all_connected_peers: () => [number, number];
  readonly generate_uuid: () => any;
  readonly get_room_from_url: () => [number, number];
  readonly update_url_with_room: (a: number, b: number) => [number, number];
  readonly validate_room_id: (a: number, b: number) => [number, number];
  readonly validate_username: (a: number, b: number) => [number, number];
  readonly validate_message: (a: number, b: number) => [number, number];
  readonly sanitize_html_content: (a: number, b: number) => [number, number];
  readonly validate_url_param: (a: number, b: number) => any;
  readonly generate_secure_room_id: () => [number, number, number, number];
  readonly check_rate_limit: (a: number, b: number, c: number, d: number) => number;
  readonly validate_file: (a: number, b: number, c: number, d: number, e: number) => number;
  readonly detect_attack_patterns: (a: number, b: number) => any;
  readonly validate_json_input: (a: number, b: number, c: number) => any;
  readonly validate_input_batch: (a: number, b: number, c: any) => any;
  readonly set_message_manager_user: (a: number, b: number) => [number, number];
  readonly send_message_enhanced: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
  readonly receive_message_from_peer: (a: any) => [number, number, number];
  readonly get_room_messages: (a: number, b: number, c: number) => any;
  readonly edit_message: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
  readonly delete_message: (a: number, b: number, c: number, d: number) => [number, number];
  readonly add_message_reaction: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
  readonly handle_typing_indicator: (a: number, b: number, c: number, d: number, e: number) => [number, number];
  readonly get_typing_users: (a: number, b: number) => any;
  readonly get_messages_for_sync: (a: number, b: number, c: number, d: number) => any;
  readonly get_room_message_stats: (a: number, b: number) => any;
  readonly create_sync_request: (a: number, b: number, c: number, d: number) => any;
  readonly handle_sync_request: (a: any) => any;
  readonly save_room_messages_to_storage: (a: number, b: number) => [number, number];
  readonly load_room_messages_from_storage: (a: number, b: number) => [number, number, number];
  readonly initialize_p2p_manager: (a: number, b: number, c: number, d: number) => [number, number];
  readonly add_known_peer: (a: number, b: number) => [number, number, number];
  readonly remove_peer_from_network: (a: number, b: number) => [number, number];
  readonly update_peer_connection_state: (a: number, b: number, c: number, d: number) => [number, number];
  readonly should_initiate_connection_to_peer: (a: number, b: number) => number;
  readonly get_connection_decision: (a: number, b: number) => any;
  readonly get_connected_peer_list: () => any;
  readonly record_peer_message_sent: (a: number, b: number, c: number) => [number, number];
  readonly record_peer_message_received: (a: number, b: number, c: number) => [number, number];
  readonly update_peer_latency: (a: number, b: number, c: number) => [number, number];
  readonly needs_mesh_repair: () => number;
  readonly get_mesh_repair_plan: () => any;
  readonly get_p2p_network_stats: () => any;
  readonly handle_connection_failure: (a: number, b: number) => any;
  readonly set_connection_strategy: (a: number, b: number) => [number, number];
  readonly cleanup_stale_peers: (a: number) => number;
  readonly get_best_peers_for_broadcast: (a: number) => any;
  readonly should_send_to_peer: (a: number, b: number, c: number) => number;
  readonly get_broadcast_plan: (a: number) => any;
  readonly initialize_logger: (a: number, b: number) => [number, number];
  readonly set_log_context: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
  readonly log_debug: (a: number, b: number, c: number, d: number) => void;
  readonly log_info: (a: number, b: number, c: number, d: number) => void;
  readonly log_warn: (a: number, b: number, c: number, d: number) => void;
  readonly log_error: (a: number, b: number, c: number, d: number) => void;
  readonly log_with_data: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
  readonly start_log_group: (a: number, b: number) => [number, number];
  readonly end_log_group: () => [number, number];
  readonly log_table: (a: any) => [number, number];
  readonly get_log_entries: (a: number, b: number) => any;
  readonly clear_log_buffer: () => [number, number];
  readonly export_logs_json: (a: number, b: number) => [number, number];
  readonly export_recent_logs_json: (a: number) => [number, number];
  readonly get_log_statistics: () => any;
  readonly enable_debug_logging: () => [number, number];
  readonly disable_debug_logging: () => [number, number];
  readonly configure_logger: (a: number, b: number, c: number, d: number) => [number, number];
  readonly search_logs: (a: number, b: number, c: number) => any;
  readonly get_logs_by_component: (a: number, b: number, c: number) => any;
  readonly get_error_summary: (a: number) => any;
  readonly create_debug_report: () => [number, number];
  readonly generate_room_encryption_key: (a: number, b: number) => [number, number, number, number];
  readonly encrypt_message_content: (a: number, b: number, c: number, d: number) => [number, number, number, number];
  readonly decrypt_message_content: (a: number, b: number) => [number, number, number, number];
  readonly export_encryption_key: (a: number, b: number, c: number, d: number) => [number, number, number, number];
  readonly import_encryption_key: (a: number, b: number, c: number, d: number) => [number, number, number, number];
  readonly list_encryption_keys: () => any;
  readonly delete_encryption_key: (a: number, b: number) => number;
  readonly initialize_storage: (a: number, b: number, c: number) => [number, number];
  readonly store_message_persistent: (a: any) => [number, number];
  readonly get_stored_messages: (a: number, b: number, c: number) => [number, number, number];
  readonly store_room_persistent: (a: any) => [number, number];
  readonly get_stored_room: (a: number, b: number) => [number, number, number];
  readonly list_stored_rooms: () => [number, number, number];
  readonly cleanup_old_storage_data: (a: number) => [number, number, number];
  readonly start_performance_monitoring: () => [number, number];
  readonly record_performance_metric: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
  readonly get_performance_summary: () => any;
  readonly start_performance_timer: (a: number, b: number) => [number, number];
  readonly end_performance_timer: (a: number, b: number) => [number, number];
  readonly increment_performance_counter: (a: number, b: number) => [number, number];
  readonly get_performance_counter: (a: number, b: number) => bigint;
  readonly memory: WebAssembly.Memory;
  readonly __wbindgen_malloc: (a: number, b: number) => number;
  readonly __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
  readonly __wbindgen_exn_store: (a: number) => void;
  readonly __externref_table_alloc: () => number;
  readonly __wbindgen_export_5: WebAssembly.Table;
  readonly __wbindgen_free: (a: number, b: number, c: number) => void;
  readonly __externref_table_dealloc: (a: number) => void;
  readonly __wbindgen_start: () => void;
}

export type SyncInitInput = BufferSource | WebAssembly.Module;
/**
* Instantiates the given `module`, which can either be bytes or
* a precompiled `WebAssembly.Module`.
*
* @param {{ module: SyncInitInput, memory?: WebAssembly.Memory }} module - Passing `SyncInitInput` directly is deprecated.
* @param {WebAssembly.Memory} memory - Deprecated.
*
* @returns {InitOutput}
*/
export function initSync(module: { module: SyncInitInput, memory?: WebAssembly.Memory } | SyncInitInput, memory?: WebAssembly.Memory): InitOutput;

/**
* If `module_or_path` is {RequestInfo} or {URL}, makes a request and
* for everything else, calls `WebAssembly.instantiate` directly.
*
* @param {{ module_or_path: InitInput | Promise<InitInput>, memory?: WebAssembly.Memory }} module_or_path - Passing `InitInput` directly is deprecated.
* @param {WebAssembly.Memory} memory - Deprecated.
*
* @returns {Promise<InitOutput>}
*/
export default function __wbg_init (module_or_path?: { module_or_path: InitInput | Promise<InitInput>, memory?: WebAssembly.Memory } | InitInput | Promise<InitInput>, memory?: WebAssembly.Memory): Promise<InitOutput>;
